site_name: Autodistill
site_url: https://docs.autodistill.com/
site_author: Roboflow
site_description: Distill large foundational models into smaller, domain-specific models for deployment
repo_name: autodistill/autodistill
repo_url: https://github.com/autodistill/autodistill
edit_uri: https://github.com/autodistill/autodistill/tree/main/docs
copyright: Roboflow 2023. All rights reserved.
favicon: logo.jpeg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roboflow
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/roboflow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/roboflow-ai/mycompany/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roboflow

extra_css:
  - stylesheets/extra.css

nav:
  - Home:
    - Home: index.md
    - Quickstart: quickstart.md
    - Supported Models: supported-models.md
    - What Model Should I Use?: what-model-should-i-use.md
    - Detection and Segmentation:
      - Base Models:
        - DETIC: https://github.com/autodistill/autodistill-detic
        - FastSAM: https://github.com/autodistill/autodistill-fastsam
        - Grounded SAM: https://github.com/autodistill/autodistill-groundedsam
        - Grounding DINO: https://github.com/autodistill/autodistill-grounding-dino
        - OWL-ViT: https://github.com/autodistill/autodistill-owlvit
        - Roboflow Universe: https://github.com/autodistill/autodistill-roboflow-universe
        - SegGPT: https://github.com/autodistill/autodistill-seggpt
      - Target Models:
        - DETR: https://github.com/autodistill/autodistill-detr
        - YOLOv5: https://github.com/autodistill/autodistill-yolov5
        - YOLOv8: https://github.com/autodistill/autodistill-yolov8
        - YOLOv8 Instance Segmentation: https://github.com/autodistill/autodistill-yolov8
        - YOLO-NAS: https://github.com/autodistill/autodistill-yolonas
    - Classification:
      - Base Models:
        - ALBEF: https://github.com/autodistill/autodistill-albef
        - AltCLIP: https://github.com/autodistill/autodistill-altclip
        - BLIP: https://github.com/autodistill/autodistill-blip
        - BLIPv2: https://github.com/autodistill/autodistill-blipv2
        - CLIP: https://github.com/autodistill/autodistill-clip
        - MetaCLIP: https://github.com/autodistill/autodistill-metaclip
        - RemoteCLIP: https://github.com/autodistill/autodistill-remoteclip
      - Target Models:
        - DINOv2: https://github.com/autodistill/autodistill-dinov2
        - YOLOv5: https://github.com/autodistill/autodistill-yolov5
        - YOLOv8: https://github.com/autodistill/autodistill-yolov8
        - ViT: https://github.com/autodistill/autodistill-vit
    - Utilities:
      - Visualize Predictions: utilities/visualize-predictions.md
      - Combine Models: utilities/combine-models.md
      - Compare Models: utilities/compare-models.md
      - Use SAHI to Detect Objects: utilities/sahi.md
      - Use Embeddings in Classification: utilities/use-embeddings-in-classification.md
      - Apply Non-Maximum Suppression (NMS): utilities/nms.md
    - Advanced:
      - Command Line Interface: command-line-interface.md
      - Image Loading: image-loading.md
      - Labeling Large Datasets: large-datasets.md
  - Library Reference:
    - Index: reference/index.md
    - Utilities: reference/utilities.md
    - Base Models:
      - Detection: reference/base-models/detection.md
      - Classification: reference/base-models/classification.md
      - Composed Model: reference/base-models/composed.md
      - Embedding Model: reference/base-models/embedding.md
    - Target Models:
      - Detection: reference/target-models/detection.md
      - Classification: reference/target-models/classification.md
    - Ontologies:
      - Caption Ontology: reference/ontologies/caption-ontology.md
      - Embedding Ontology: reference/ontologies/embedding-ontology.md
  - Contributing: contributing.md

extra_css:
  - stylesheets/extra.css

theme:
  name: 'material'
  logo: 'logo.jpeg'
  favicon: 'logo.jpeg'
  palette:
    # Palette for light mode
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: 'custom'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: 'docs/custom_theme'
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections
    - content.code.copy

plugins:
  - social:
      cards_layout_dir: layouts
      cards_layout: custom
      debug: true
  - mkdocstrings
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_javascript:
  - "https://widget.kapa.ai/kapa-widget.bundle.js"
  - "javascript/init_kapa_widget.js"